language: r

before_install:
  - tlmgr install preprint la­tex-graph­ics amsmath

cache: packages
sudo: false

os:
  - linux
  - osx

r_github_packages:
  - jimhester/covr

after_success:
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then echo 'covr::coveralls(quiet=FALSE)' | R --vanilla; fi
