language: r
cache: packages
sudo: false

before_install:
  - tlmgr install index

os:
  - linux
  - osx

r_github_packages:
  - jimhester/covr

after_success:
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then echo 'covr::coveralls(quiet=FALSE)' | R --vanilla; fi
